# --- Configuration du Log Guardian ---

# Nombre d'échecs avant bannissement
BAN_THRESHOLD=8

# Dossiers de travail
VAR_DIR="var"
LOG_DIR="log"
CONF_DIR="config"

# Nom des fichiers
BANNED_DB="banned_ips.db"
REPORT_LOG="firewall_activity.log"
WHITELIST="whitelist.conf"